### ISSUE TITLE
Formulate a consise Mission

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/smart-cities-public-code#1]
The ingredients of our mission for Smart Cities? Public Code! are:

1. Disseminating Code == Code as philosphical aspect
2. Public Code as a practical answer
3. and connecting the two

## How to do this?

1. Create a new file called `mission.md` in the top level of the project.
2. Formulate a mission for this project in that file
3. Link to that mission from `index.md`
4. Create a Pull Request with your changes and have it reviewed by one of the maintainers on the project.

**Comment by clausmullie** [comment]
I have done some work on code = code in security studies (ie algorithmic analysis of risk in financial transactions and cctv images, by which 'the other' , 'outside the norm' , gets further and automatically marginalised as a threat). Happy to support where I can.
